[package]
name = "peek-reverse-proxy"
version = "0.0.1"
edition = "2021"
description = "A simple reverse proxy to peek into requests"
license = "MIT"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
hyper-reverse-proxy = "0.5.1"
hyper = { version = "0.14.17", features = ["full"] }
tokio = { version = "1.17.0", features = ["full"] }
url = "2.2.2"
log = "0.4.14"    
env_logger = "0.9.0"
futures = "0.3.21"  
tokio-core = "0.1.18" 
