name: Build

on:
  push:
    branches:
      - "main"
  pull_request:
    branches:
      - "*"

jobs:
  build-native:
    name: Build on native hardware
    strategy:
      fail-fast: false
      matrix:
        toolchain:
          - stable
          - beta
          - nightly
          - 1.56.0 # msrv
        config:
          - node: ubuntu-latest
          - node: windows-latest
          - node: macos-latest
    runs-on: ${{ matrix.config.node }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3.0.0

      - uses: actions-rs/toolchain@v1
        with:
          toolchain: ${{ matrix.toolchain }}
          override: true

      - uses: Swatinem/rust-cache@v1.4.0

      - name: Build Dev
        run: cargo build --all-features --workspace  --examples

      - name: Build Release
        run: cargo build --release --all-features --workspace --examples

  build-cross:
    name: Build for foreign hardware via cross
    strategy:
      fail-fast: false
      matrix:
        toolchain:
          - stable
          - beta
          - nightly
          - 1.56.0 # msrv
        config:
          # linux aarch64
          - node: ubuntu-latest
            arch: aarch64-unknown-linux-gnu
          - node: ubuntu-latest
            arch: aarch64-unknown-linux-musl

          # linux x86
          - node: ubuntu-latest
            arch: x86_64-unknown-linux-gnu
          - node: ubuntu-latest
            arch: x86_64-unknown-linux-musl
          - node: ubuntu-latest
            arch: x86_64-linux-android

          # windows aarch64
          - node: windows-latest
            arch: aarch64-pc-windows-msvc
          - node: windows-latest
            arch: x86_64-pc-windows-msvc
          
          # apple aarch64
          - node: macos-latest
            arch: aarch64-apple-darwin

    runs-on: ${{ matrix.config.node }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3.0.0

      - uses: docker-practice/actions-setup-docker@master
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      
      - name: Install
        run: cargo install cross

      - uses: actions-rs/toolchain@v1
        with:
          toolchain: ${{ matrix.toolchain }}
          override: true

      - name: Build Dev
        run: rustup target add ${{ matrix.config.arch }}
      
      - name: Build Dev
        run: cross build --target ${{ matrix.config.arch }} --all-features --workspace  --examples
      
      - name: Build Relese
        run: cross build --target ${{ matrix.config.arch }} --all-features --release --workspace  --examples